---
name: terraform-lint

"on": [pull_request]

jobs:
  terraform-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
      - name: Lint Terraform
        uses: actionshub/terraform-lint@main
