---
name: terraform-lint

"on": [pull_request]

jobs:
  terraform-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: Lint Terraform
        uses: actionshub/terraform-lint@main
