---
name: terraform-lint

"on": [pull_request]

jobs:
  terraform-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4
      - name: Lint Terraform
        uses: actionshub/terraform-lint@main
