---
name: terraform-lint

"on": [pull_request]

jobs:
  terraform-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - name: Lint Terraform
        uses: actionshub/terraform-lint@main
